---
- name: Check if apt key file exists
  stat:
    path: /usr/share/keyrings/cznic-labs-pkg.gpg
  register: file_exists

- name: Add cznic labs pkg apt key.
  get_url:
    url: "{{ bird2_apt_gpg_key }}"
    dest: /usr/share/keyrings/cznic-labs-pkg.gpg
  when: not file_exists.stat.exists

- name: Add bird2 repository.
  apt_repository:
    repo: "{{ bird2_apt_repository }}"
    state: present
    update_cache: true

- name: Install bird2 package
  ansible.builtin.package:
    name: "bird2"
    state: latest

# Log
- name: Create bird log file
  ansible.builtin.file:
    dest: "{{ bird2_log_file }}"
    state: touch
    owner: bird
    group: bird
    mode: 0644
    modification_time: preserve
    access_time: preserve

# Service
- name: Ensure bird is started and enabled at boot
  ansible.builtin.service:
    name: bird
    state: "{{ bird2_service_state }}"
    enabled: "{{ bird2_service_enabled }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Allow the Debian-snmp user to sudo /usr/sbin/birdc
  community.general.sudoers:
    name: bird-snmp-extend
    state: present
    user: Debian-snmp
    commands: /usr/sbin/birdc
  when: "bird2_snmp_enabled|bool"

# Prometheus Exporter
- include_tasks: "{{ role_path }}/tasks/setup-bird-exporter.yml"
  when: "bird2_exporter_enabled|bool"

# Birdwatcher
- include_tasks: "{{ role_path }}/tasks/setup-birdwatcher.yml"
  when: "bird2_birdwatcher_enabled|bool"

